### ISSUE TITLE
Service providers priority and Gates

### ISSUE THREAD

**Issue by bessone** [InnoGE/laravel-policy-soft-cache#10] opened 2024-01-04 15:50 UTC
Hello,

in my application I already use the Gate::before to check the superadmin, if so all the gates and policies are bypassed, the code in AuthServiceProvider is something like:

`    public function boot()
    {
        $this->registerPolicies();

        Gate::before(function ($user, $ability) {
            return $user->isAdmin() ? true : null;
        });
    }
`

by enabling this package my check is ignored, this is because the boot method of LaravelPolicySoftCacheServiceProvider is executed before the boot of my AuthServiceProvider.

My solution was to disable package autodiscovery in composer.json

`
    "extra": {
        "laravel": {
            "dont-discover": [
                "innoge/laravel-policy-soft-cache"
            ]
        }
    },
`

 and insert the LaravelPolicySoftCacheServiceProvider in the app.php after the app AuthServiceProvider.

Is this the only solution or is there a way to give priority to the various Gate::before?
I'm writing this because maybe it can help someone else

Many thanks!

**Comment by geisi** [comment] 2024-01-04 21:19
@bessone,

Thank you for bringing this issue to our attention. We were able to reproduce it and have since updated our documentation to provide guidance for other users encountering the same problem. You can find the detailed instructions in the "Known Issues" section of our README file on GitHub: [Laravel Policy Soft Cache Known Issues](https://github.com/InnoGE/laravel-policy-soft-cache?tab=readme-ov-file#known-issues).

We considered resolving this by disabling auto-discovery for our package. However, we realized that such a change could lead to a significant breaking change and introduce additional manual steps for installation and configuration. To balance the ease of use and robustness of our package, we have decided that documenting the issue and its resolution is the most effective approach at this time.

Your contribution has been invaluable, and we appreciate your support in helping us improve our package.

**Closed as completed by geisi** 2024-01-04 21:19 UTC
